name: 'Publish github pre-release'
description: 'Gradle build and publish github pre-release'

inputs:
  files:
    description: 'Globs of files to include in pre-release'
    default: '*/build/libs/*.jar'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/java-gradle-repo-setup.yml
      with:
        arguments: shadowJar

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: ${{ inputs.files }}
